enabled: true
configs:
  default:
    enabled: false
    endpoints: ["localhost:2379"]
    auto_sync_interval: "3s"
    dial_timeout: "3s"
    dial_keep_alive_time: "3s"
    dial_keep_alive_timeout: "3s"
    username: ""
    password: ""
    reject_old_cluster: false
    permit_without_stream: false
